server:
  port: 28771
spring:
  application:
    name: tx-lcn-server
  redis:
    host: 192.168.89.4
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/tx-manager?characterEncoding=utf-8&useSSL=false
  cloud:
    host: 127.0.0.1
    port: 8500
    consul:
      discovery:
        service-name: tx-lcn-server
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
      config:
        enabled: true
        format: yaml
        data-key: data #表示consul上面的KEY值(或者说文件的名字) 默认是data