spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/springcloud_test?characterEncoding=utf-8&useSSL=false
  cloud:
    stream:
      bindings:
        huiStream:
          group: hui
          content-type: application/json
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
logging:
    level:
      com.hui.springcloud.common.mapper: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
#PRODUCT-SERVER:
#  ribbon:
#    NFLoadBalancerRuleClassName: 配置负载均衡（全类名）