spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ithuhui/hui-base-springcloud-config-repo
          username: ithuhui
          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090